name: CI Pipeline
on:
 push:
 branches: [ "main" ] # jalankan saat ada push ke main
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout Repository
 uses: actions/checkout@v3
 - name: Setup Python
 uses: actions/setup-python@v4
 with:
 python-version: '3.x'
 - name: Run Program
 run: python hello.py
